[package]
name = "golden_token"
version = "0.1.0"

[dependencies]
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts", ref = "v0.8.0-beta.1" }
starknet = "2.1.1"
arcade_account = { git = "https://github.com/ArichiMasaomi/arcade-account" }

[lib]

[[target.starknet-contract]]
allowed-libfuncs-list.name = "experimental"
allowed-libfuncs = true
